### ISSUE TITLE
Core functions all shows as "deprecated"

### ISSUE THREAD

**Issue by AFwcxx** [marlonfan/coc-phpls#41]
**Describe the bug**
The intelephense shows all core functions that ships with php as deprecated
Example: [intelephense 1007] [H] 'strtolower' is deprecated.

**Desktop (please complete the following information):**
vim version: NVIM v0.4.3
node version: v13.3.0
coc.nvim version: 0.0.74-d83536aa4e
term: iTerm.app
platform: darwin

**Comment by dvaqueiro** [comment]
Same issue

**Comment by mubisco** [comment]
**Describe the bug**
Same issue, all php native functions tagged as deprecated.

**Desktop (please complete the following information):**
vim version: NVIM v0.4.3
node version: v12.13.1
coc.nvim version: 0.0.74-d83536aa4e
term: screen-256color
platform: linux

Maybe this can help:
## Output channel: phpls

[Info  - 15:16:53] Initialising intelephense 1.3.5
[Info  - 15:16:53] Reading state from /home/xbellon/.config/coc/extensions/coc-phpls-data/5e572f5e.
[Info  - 15:16:54] Initialised in 781 ms
[Info  - 15:16:54] Intelephense 1.2.3
[Info  - 15:16:55] Indexing started.
[Info  - 15:16:55] Indexing ended. 1 files indexed in 0s.
[Info  - 15:16:55] Writing state to /home/xbellon/.config/coc/extensions/coc-phpls-data/5e572f5e.
[Info  - 15:16:55] Wrote state in 0.7s.

**Comment by marlonfan** [comment]
Hi guys, I don't see this problem in my environment.  

Can you turn on verbose mode so I can see CocInfo Output?

@mubisco @dvaqueiro @AFwcxx

**Comment by AFwcxx** [comment]
Not sure how to turn on the verbose mode, 
But when I add the line as shown in the screenshot, the intelephense show that the function base64_decode is deprecated.
![Screenshot 2019-12-17 at 13 18 45](https://user-images.githubusercontent.com/7138726/70966974-d7db1600-20cf-11ea-8e5e-8f51b62e3559.png)

This is what shown in the coc log:

2019-12-17T13:16:41.396 INFO (pid:20444) [services] - registered service "highlight"

2019-12-17T13:16:41.471 INFO (pid:20444) [plugin] - coc 0.0.74-d83536aa4e initialized with node: v13.3.0

2019-12-17T13:16:41.477 INFO (pid:20444) [language-client-index] - highlight started with 20445

2019-12-17T13:16:41.561 INFO (pid:20444) [services] - highlight server state change: starting => running

2019-12-17T13:16:48.391 INFO (pid:20444) [language-client-index] - phpls started with 20450

2019-12-17T13:17:53.624 INFO (pid:20444) [completion-complete] - Results from: phpls

2019-12-17T13:17:54.428 INFO (pid:20444) [completion-complete] - Results from: around,buffer,phpls

2019-12-17T13:17:56.108 INFO (pid:20444) [completion-complete] - Results from: around,buffer,phpls

2019-12-17T13:17:56.806 INFO (pid:20444) [completion-complete] - Results from: around,phpls

2019-12-17T13:18:02.164 INFO (pid:20444) [completion-complete] - Results from: around,buffer

2019-12-17T13:18:02.318 INFO (pid:20444) [completion-complete] - Results from: around,buffer

**Comment by tomsteg** [comment]
I get "[intelephense 1010] [E] Undefined function" for example for is_null, sleep, Exception .

Coc Log:
2019-12-18T11:16:07.986 INFO (pid:93964) [services] - registed service "languageserver.intelephense"
2019-12-18T11:16:07.988 INFO (pid:93964) [services] - intelephense state change: stopped => starting
2019-12-18T11:16:08.003 INFO (pid:93964) [services] - registed service "eslint"
2019-12-18T11:16:08.207 INFO (pid:93964) [language-client-index] - languageserver.intelephense started with 93969
2019-12-18T11:16:08.214 INFO (pid:93964) [language-client-index] - phpls started with 93970
2019-12-18T11:16:08.216 INFO (pid:93964) [plugin] - coc 0.0.74-bc017b02e6 initialized with node: v13.3.0
2019-12-18T11:16:08.240 INFO (pid:93964) [services] - registed service "json"
2019-12-18T11:16:08.240 INFO (pid:93964) [services] - Json language server state change: stopped => starting
2019-12-18T11:16:08.247 INFO (pid:93964) [language-client-index] - json started with 93973
2019-12-18T11:16:08.324 INFO (pid:93964) [services] - Json language server state change: starting => running
2019-12-18T11:16:08.327 INFO (pid:93964) [services] - service json started
2019-12-18T11:16:09.200 INFO (pid:93964) [services] - intelephense state change: starting => running
2019-12-18T11:16:09.201 INFO (pid:93964) [services] - service languageserver.intelephense started

**Comment by marlonfan** [comment]
@AFwcxx @dvaqueiro @mubisco @tomsteg Hi, please update to latest version. Does it work?

**Comment by Norbytus** [comment]
Hm i have this problem too, after last update, but before updae all was normal

**Comment by marlonfan** [comment]
@Norbytus Because of some problems with the upstream LSP server, it should have been fixed

**Comment by AFwcxx** [comment]
> @AFwcxx @dvaqueiro @mubisco @tomsteg Hi, please update to latest version. Does it work?

Seems like it's still behaving the same.

**Comment by mubisco** [comment]
> @AFwcxx @dvaqueiro @mubisco @tomsteg Hi, please update to latest version. Does it work?

Currently with coc-phpls 2.1.6
Still marks core functions as deprecated

**Comment by Terseus** [comment]
> @Norbytus Because of some problems with the upstream LSP server, it should have been fixed

Can confirm that with coc-phpls 2.1.7 the problem still exists, core functions and interfaces (e.g. `\Serializable`) are marked as deprecated.

**Comment by tomsteg** [comment]
I can confirm, that the problem still exists with coc-phpls 2.1.7. The error message is 'undefined function', when an error is marked on standard functions. There is an other problem, that maybe correlates: In my composer.json I have an autoload section for autoloading classes for psr-4 and classmap. Those classes are marked as 'undefined type', but in php on the server everything works fine.

**Comment by rosmanov** [comment]
The same problem here.
```
vim version: NVIM v0.4.3
node version: v12.13.1
coc.nvim version: 0.0.74-bc017b02e6
term: screen-256color
platform: linux
```

**Comment by stormpat** [comment]
Same issue

```
vim version: NVIM v0.4.3
node version: v13.3.0
coc.nvim version: 0.0.74-d83536aa4e
term: xterm-kitty
platform: darwin
```

**Comment by tomsteg** [comment]
@stormpat Yes, that fixed everything. Thank you very much. Great and simple.

**Comment by Terseus** [comment]
I can confirm that the issue goes away after deleting the coc-phpls cache.

Thanks a lot for the info @stormpat ^_^

**Comment by AFwcxx** [comment]
> Same issue
> 
> ```
> vim version: NVIM v0.4.3
> node version: v13.3.0
> coc.nvim version: 0.0.74-d83536aa4e
> term: xterm-kitty
> platform: darwin
> ```
> 
> EDIT.
> 
> This seemed to be a cache issue. Anyone still facing this delete the cache, restart vim and let coc reindex the files.
> 
> ```
> > rm -rf ~/.config/coc/extensions/coc-phpls-data
> ```

Use this to rectify issue.

**Comment by dvaqueiro** [comment]
Yes, remove the cache solve the problem in my case. Thanks
